spring:
  profiles:
    active: mysql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch?characterEncoding=utf8&serverTimezone=Asia/Seoul
      username: batch
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      auto-commit: false
      connection-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 10
---
spring:
  profiles:
    active: oracle
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    hikari:
      jdbc-url: jdbc:oracle:thin:@192.168.1.113:1521:orcl
      username: kolas
      password: eco_kolas3#
      driver-class-name: oracle.jdbc.driver.OracleDriver
      auto-commit: false
      connection-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 10
#logging:
#  level:
#    root: DEBUG
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE